name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . -t ledcontrollerapi
    - name: Tag the Docker image
      run: docker tag ledcontrollerapi docker.pkg.github.com/swissbuechi/ledcontrollerapi/ledcontrollerapi:latest
    - name: Publish the Docker image
      run: docker push docker.pkg.github.com/swissbuechi/ledcontrollerapi/ledcontrollerapi:latest
